SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `DH-Project` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `DH-Project`;

CREATE TABLE `Products` (
  `Id` int(11) NOT NULL,
  `Name` char(255) NOT NULL,
  `Price` int(10) UNSIGNED NOT NULL,
  `Description` text NOT NULL,
  `Category` char(255) NOT NULL,
  `Size` char(255) NOT NULL,
  `Colour` char(255) NOT NULL,
  `Brand` char(255) NOT NULL,
  `Picture` longtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `Products`
  ADD PRIMARY KEY (`Id`);


ALTER TABLE `Products`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
